
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "app/componentes/header";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Future World",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log('hola mundo layout')
  return (
    <html lang="en">
      <body className={inter.className}>
     
      

        {children}
        </body>
    </html>
  );
}